### ISSUE TITLE
Deploy pip, install as a python binary

### ISSUE THREAD

**Issue by Guibod** [newmediadenver/evegenie#24]
Hi,
could you please deploy this tool, as a pip package instead of a git repository please.

I'd be really glad to use it this way:
```Shell
pip install evegenie
evegenie sample.json
```

Instead i'm forced to :
```Shell
git clone https://github.com/drud/evegenie.git
cd evegenie
pip -r requirements
python geneve.py sample.json
```
please notice that the binary is not named as the project i've just cloned. Which is a little bit confusing.

Please check this out: 
https://chriswarrick.com/blog/2014/09/15/python-apps-the-right-way-entry_points-and-scripts/

**Comment by rfay** [comment]
I apologize, we're not maintaining this repo any more. You're welcome to fork it and move on with it. We didn't want to take it off github, but it's not something we have any reason to maintain now. If you do fork and maintain it, let us know and we'll add that info to the readme.
